
package Vista;

import Controlador.EstudioControlador;
import Controlador.PacienteControlador;
import Controlador.ProfesionalControlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Modelo.Fecha;
import Controlador.ArchivoControlador;

public class VentanaCargar extends javax.swing.JFrame {

    private PacienteControlador pControl;
    private ProfesionalControlador profControl;
    private EstudioControlador eControl;
    private VentanaPrincipal ventanaPrincipal;
    private List<Integer> analisisTemporales = new ArrayList<>();
    

    public VentanaCargar(PacienteControlador pControl, ProfesionalControlador profControl, EstudioControlador eControl, VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.pControl = pControl;
        this.profControl = profControl;
        this.eControl = eControl;
        this.ventanaPrincipal = ventanaPrincipal;
        this.setLocationRelativeTo(null);
        
        //Autocompleta la fecha de realizacion con el dia de hoy
        java.time.LocalDate hoy = java.time.LocalDate.now();
        txtDiaRealizacion.setText(String.valueOf(hoy.getDayOfMonth()));
        txtMesRealizacion.setText(String.valueOf(hoy.getMonthValue()));
        txtAnioRealizacion.setText(String.valueOf(hoy.getYear()));
        
        
        cmbAnalisisDisponibles.removeAllItems(); 
        
        
        for (java.util.Map.Entry<Integer, String> entry : eControl.getCatalogo().entrySet()) {
            
            
            cmbAnalisisDisponibles.addItem(entry.getKey() + " - " + entry.getValue());
        }
    }

    public VentanaCargar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoPaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDniPaciente = new javax.swing.JTextField();
        txtTelefonoPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMailPaciente = new javax.swing.JTextField();
        chkObraSocial = new javax.swing.JCheckBox();
        btnGuardarPaciente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDniEstudio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMatriculaEstudio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDiaRealizacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMesRealizacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAnioRealizacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDiaEntrega = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMesEntrega = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtAnioEntrega = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnAgregarAnalisis = new javax.swing.JButton();
        btnEliminarAnalisis = new javax.swing.JButton();
        btnGuardarEstudio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAnalisis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cmbAnalisisDisponibles = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreProfesional = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoProfesional = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMatriculaProfesional = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoProfesional = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMailProfesional = new javax.swing.JTextField();
        btnGuardarProfesional = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre :");

        txtNombrePaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Apellido :");

        txtApellidoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("DNI :");

        txtDniPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTelefonoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Mail :");

        txtMailPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        chkObraSocial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkObraSocial.setText("Obra social");
        chkObraSocial.setMaximumSize(new java.awt.Dimension(100, 50));
        chkObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkObraSocialActionPerformed(evt);
            }
        });

        btnGuardarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardarPaciente.setText("Guardar");
        btnGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPacienteActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pacienteJJE.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Ingrese la informacion");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("de un paciente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(txtApellidoPaciente)
                                    .addComponent(txtDniPaciente)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 6, Short.MAX_VALUE)
                                        .addComponent(jLabel25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)))
                        .addGap(139, 139, 139))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellidoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDniPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(chkObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        jTabbedPane2.addTab("Paciente", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DNI paciente");

        txtDniEstudio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Matrícula profesional");

        txtMatriculaEstudio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Fecha de realización");

        txtDiaRealizacion.setEditable(false);
        txtDiaRealizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDiaRealizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaRealizacionActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("/");

        txtMesRealizacion.setEditable(false);
        txtMesRealizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("/");

        txtAnioRealizacion.setEditable(false);
        txtAnioRealizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Fecha de entrega");

        txtDiaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDiaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaEntregaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("/");

        txtMesEntrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("/");

        txtAnioEntrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAnioEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioEntregaActionPerformed(evt);
            }
        });

        cmbEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En elaboracion", "Finalizado", "Retirado", "Enviado" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Estado");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Análisis");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Análisis agregados:");

        btnAgregarAnalisis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarAnalisis.setText("Agregar");
        btnAgregarAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAnalisisActionPerformed(evt);
            }
        });

        btnEliminarAnalisis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminarAnalisis.setText("Eliminar análisis");
        btnEliminarAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAnalisisActionPerformed(evt);
            }
        });

        btnGuardarEstudio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardarEstudio.setText("Guardar estudio");
        btnGuardarEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstudioActionPerformed(evt);
            }
        });

        txtAreaAnalisis.setEditable(false);
        txtAreaAnalisis.setColumns(20);
        txtAreaAnalisis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAreaAnalisis.setRows(5);
        txtAreaAnalisis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtAreaAnalisis);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbAnalisisDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAnalisisDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAnalisisDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnalisisDisponiblesActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/estudioJJE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 324, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDiaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiaRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMesRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMesEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAnioRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAnioEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDniEstudio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                        .addComponent(txtMatriculaEstudio)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cmbAnalisisDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgregarAnalisis)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(btnGuardarEstudio)))
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnEliminarAnalisis)
                                        .addComponent(jLabel29)))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDniEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMatriculaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnioRealizacion)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiaRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtMesRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDiaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txtMesEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtAnioEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btnAgregarAnalisis)
                    .addComponent(cmbAnalisisDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(92, 92, 92)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Estudio", jPanel4);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre :");

        txtNombreProfesional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProfesionalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Apellido :");

        txtApellidoProfesional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Matricula :");

        txtMatriculaProfesional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Teléfono :");

        txtTelefonoProfesional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Mail :");

        txtMailProfesional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnGuardarProfesional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardarProfesional.setText("Guardar");
        btnGuardarProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProfesionalActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Ingrese la informacion");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("de un profesional");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/profesionalJJe.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardarProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(62, 62, 62))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoProfesional)
                                    .addComponent(txtTelefonoProfesional)
                                    .addComponent(txtMailProfesional)
                                    .addComponent(txtMatriculaProfesional)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNombreProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(110, 110, 110))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtApellidoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatriculaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoProfesional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMailProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        jTabbedPane2.addTab("Profesional", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Paciente");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePacienteActionPerformed

    private void chkObraSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkObraSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkObraSocialActionPerformed

    private void btnGuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPacienteActionPerformed
        String dni = txtDniPaciente.getText().trim();
        String nombre = txtNombrePaciente.getText().trim();
        String apellido = txtApellidoPaciente.getText().trim();
        String telefono = txtTelefonoPaciente.getText().trim();
        String mail = txtMailPaciente.getText().trim().toLowerCase(); // Lo pasamos a minúscula acá mismo
        boolean obraSocial = chkObraSocial.isSelected();

        // Valida campos vacios
        if (dni.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || mail.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
            return;
        }
        
        // Valida nombre y apellido
        if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$") || !apellido.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
            JOptionPane.showMessageDialog(null, "El nombre y el apellido solo pueden contener letras.");
            return;
        }
        
        // Valida DNI
        if (!pControl.dniValido(dni)){
            JOptionPane.showMessageDialog(null, "El DNI debe tener 7 u 8 dígitos numéricos.");
            return;
        }

        // validacion de mail
        if (!mail.contains("@")) {
            JOptionPane.showMessageDialog(null, "Error: El correo debe contener un '@'.");
            return;
        }
        
        boolean esGmail = mail.endsWith("@gmail.com") || mail.endsWith("@gmail.com.ar");
        boolean esHotmail = mail.endsWith("@hotmail.com") || mail.endsWith("@hotmail.com.ar");

        if (!esGmail && !esHotmail) {
            JOptionPane.showMessageDialog(null, "Solo se permiten correos de @gmail o @hotmail.");
            return;
        }
        
        
        // Valida telefono (Celular Argentino)
        if (!telefono.matches("^(?:\\+549|549)?0?\\d{10}$")) {
            JOptionPane.showMessageDialog(null, "Ingrese un celular válido de Argentina de 10 dígitos (Ej: 2664123456).");
            return;
        }
        
        // Valida que no se repita
        if (pControl.buscarPacientePorDni(dni) != null) {
            JOptionPane.showMessageDialog(null, "Ya existe un paciente con ese DNI.");
            return;
        }

        // Guarda
        pControl.setDniPaciente(dni);
        pControl.setNombrePaciente(nombre);
        pControl.setApellidoPaciente(apellido);
        pControl.setTelefono(telefono);
        pControl.setMail(mail);
        pControl.setObraSocial(obraSocial);
        pControl.listaAgregarPaciente();
        pControl.prepararNuevoPaciente();
        
        ArchivoControlador archivoCtrl = new ArchivoControlador("pacientes.txt", "profesionales.txt", "estudios.txt");
        archivoCtrl.guardarPacientes(pControl.getListaPaciente());

        JOptionPane.showMessageDialog(null, "Paciente guardado correctamente.");

        // Limpia campos
        txtDniPaciente.setText("");
        txtNombrePaciente.setText("");
        txtApellidoPaciente.setText("");
        txtTelefonoPaciente.setText("");
        txtMailPaciente.setText("");
        chkObraSocial.setSelected(false);
    }//GEN-LAST:event_btnGuardarPacienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ventanaPrincipal.setVisible(true); // muestra la principal
        this.dispose(); // cierra y libera memoria de esta ventana
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProfesionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfesionalActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ventanaPrincipal.setVisible(true); // muestra la principal
        this.dispose(); // cierra y libera memoria de esta ventana
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDiaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaEntregaActionPerformed

    private void txtDiaRealizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaRealizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaRealizacionActionPerformed

    private void btnGuardarProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProfesionalActionPerformed
        String matricula = txtMatriculaProfesional.getText().trim();
        String nombre = txtNombreProfesional.getText().trim();
        String apellido = txtApellidoProfesional.getText().trim();
        String telefono = txtTelefonoProfesional.getText().trim();
        String mail = txtMailProfesional.getText().trim().toLowerCase();
    

    // Valida campos vacios
    if (matricula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || mail.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
        return;
    }
    // Valida que nombre y apellido solo tengan letras
        if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$") || !apellido.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
            JOptionPane.showMessageDialog(null, "El nombre y el apellido solo pueden contener letras.");
            return;
        }
    // Valida que matricula sea numerica y tenga la longitud correcta (4 a 6 digitos para MN/MP)
        if (!matricula.matches("\\d{4,6}")) {
            JOptionPane.showMessageDialog(null, "La matrícula debe contener entre 4 y 6 números (Formato Nacional/Provincial).");
            return;
        }

        // Valida formato de Mail
        if (!mail.matches("^[a-z0-9._%+-]+@(gmail|hotmail)\\.com(\\.ar)?$")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un correo electrónico válido (ejemplo@mail.com).");
            return;
        }
        
     
    // Valida teléfono (Celular Argentino)
        if (!telefono.matches("^(?:\\+549|549)?0?\\d{10}$")) {
            JOptionPane.showMessageDialog(null, "Ingrese un celular válido de Argentina de 10 dígitos (Ej: 2664123456).");
            return;
        }
    // Valida que no exista ya
    int matriculaInt = convertirAEntero(matricula);
    if (profControl.buscarProfesional(matriculaInt) != null) {
        JOptionPane.showMessageDialog(null, "Ya existe un profesional con esa matrícula.");
        return;
    }

    // 5. Guardar
    profControl.registrarNuevoProfesional(matriculaInt, apellido, nombre, telefono, mail);
    
    // Persistencia de archivo
        ArchivoControlador archivoCtrl = new ArchivoControlador("pacientes.txt", "profesionales.txt", "estudios.txt");
        archivoCtrl.guardarProfesionales(profControl.getListaProfesionales());
        // --------------------------------------

    JOptionPane.showMessageDialog(null, "Profesional guardado correctamente.");

    // Limpia campos
    txtMatriculaProfesional.setText("");
    txtNombreProfesional.setText("");
    txtApellidoProfesional.setText("");
    txtTelefonoProfesional.setText("");
    txtMailProfesional.setText("");
    }//GEN-LAST:event_btnGuardarProfesionalActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnAgregarAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnalisisActionPerformed
        String seleccionado = cmbAnalisisDisponibles.getSelectedItem().toString();
        String codigoStr = seleccionado.split(" - ")[0]; 
        
        //convertimos el codigo a int
        int codigo = convertirAEntero(codigoStr);
        
        if (analisisTemporales.contains(codigo)) {
            JOptionPane.showMessageDialog(null, "Ese análisis ya fue agregado a la lista.");
            return;
        }
        
        analisisTemporales.add(codigo);
        txtAreaAnalisis.append(seleccionado + "\n");
    }//GEN-LAST:event_btnAgregarAnalisisActionPerformed

    private void btnEliminarAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAnalisisActionPerformed
        // 1. Verificamos que haya algo para borrar
        if (analisisTemporales.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ningún análisis agregado para eliminar.");
            return;
        }

        // 2. Le preguntamos al usuario qué código quiere sacar
        String codigoStr = JOptionPane.showInputDialog(this, "Ingrese el CÓDIGO del análisis que desea eliminar:");

        // Si el usuario presiona "Cancelar" o cierra la ventanita, cortamos acá
        if (codigoStr == null || codigoStr.trim().isEmpty()) {
            return; 
        }
        
        codigoStr = codigoStr.trim();

        // 3. validacion de codigo
        if (!codigoStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números enteros.");
            return;
        }

        // Usamos nuestro propio método
        int codigoAEliminar = convertirAEntero(codigoStr);

        if (analisisTemporales.contains(codigoAEliminar)) {
            analisisTemporales.remove(Integer.valueOf(codigoAEliminar));
            
            txtAreaAnalisis.setText("");
            for (int cod : analisisTemporales) {
                String nombre = eControl.obtenerNombre(cod);
                txtAreaAnalisis.append(cod + " - " + nombre + "\n");
            }
            JOptionPane.showMessageDialog(this, "Análisis eliminado con éxito.");
            
        } else {
            JOptionPane.showMessageDialog(this, "Ese código no se encuentra en la lista de análisis agregados.");
        }
    }//GEN-LAST:event_btnEliminarAnalisisActionPerformed

    private void btnGuardarEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstudioActionPerformed
        //BOTON DE GUARDAR ESTUDIO
        String dniPaciente = txtDniEstudio.getText().trim();
        String matriculaStr = txtMatriculaEstudio.getText().trim();
        String diaR = txtDiaRealizacion.getText().trim();
        String mesR = txtMesRealizacion.getText().trim();
        String anioR = txtAnioRealizacion.getText().trim();
        String diaE = txtDiaEntrega.getText().trim();
        String mesE = txtMesEntrega.getText().trim();
        String anioE = txtAnioEntrega.getText().trim();
        String estado = cmbEstado.getSelectedItem().toString();

        if (dniPaciente.isEmpty() || matriculaStr.isEmpty() || diaR.isEmpty() || mesR.isEmpty() || anioR.isEmpty() || diaE.isEmpty() || mesE.isEmpty() || anioE.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
            return;
        }

        if (pControl.buscarPacientePorDni(dniPaciente) == null) {
            JOptionPane.showMessageDialog(null, "No existe un paciente con ese DNI.");
            return;
        }

        if (!matriculaStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "La matrícula debe ser numérica.");
            return;
        }
        
        // REGLA DEL PROFE: No es fecha, usamos método propio
        int matricula = convertirAEntero(matriculaStr);
        if (profControl.buscarProfesional(matricula) == null) {
            JOptionPane.showMessageDialog(null, "No existe un profesional con esa matrícula.");
            return;
        }

        if (analisisTemporales.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe agregar al menos un análisis.");
            return;
        }

        // VALIDACIÓN DE FECHAS SIN EXCEPCIONES
        if (!diaR.matches("\\d+") || !mesR.matches("\\d+") || !anioR.matches("\\d+") || 
            !diaE.matches("\\d+") || !mesE.matches("\\d+") || !anioE.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Error: Ingrese solo números enteros en los campos de fecha.");
            return;
        }

        //parse para fecha
        int dR = Integer.parseInt(diaR);
        int mR = Integer.parseInt(mesR);
        int aR = Integer.parseInt(anioR);
        int dE = Integer.parseInt(diaE);
        int mE = Integer.parseInt(mesE);
        int aE = Integer.parseInt(anioE);

        java.time.LocalDate hoy = java.time.LocalDate.now();
        int anioActual = hoy.getYear();

        if (mR < 1 || mR > 12 || mE < 1 || mE > 12) {
            JOptionPane.showMessageDialog(null, "Error: El mes debe estar entre 1 y 12.");
            return;
        }
        if (dR < 1 || dR > 31 || dE < 1 || dE > 31) {
            JOptionPane.showMessageDialog(null, "Error: El día debe estar entre 1 y 31.");
            return;
        }
        if (aR < anioActual - 1 || aE > anioActual + 5) {
            JOptionPane.showMessageDialog(null, "Error: El año ingresado no es válido.");
            return;
        }

        if (((mR == 4 || mR == 6 || mR == 9 || mR == 11) && dR > 30) || 
            ((mE == 4 || mE == 6 || mE == 9 || mE == 11) && dE > 30)) {
            JOptionPane.showMessageDialog(null, "Error: Uno de los meses ingresados solo tiene 30 días.");
            return;
        }
        if ((mR == 2 && dR > 29) || (mE == 2 && dE > 29)) {
            JOptionPane.showMessageDialog(null, "Error: Febrero no puede tener más de 29 días.");
            return;
        }

        boolean fechaInvalida = false;
        if (aE < aR) {
            fechaInvalida = true;
        } else if (aE == aR && mE < mR) {
            fechaInvalida = true;
        } else if (aE == aR && mE == mR && dE < dR) {
            fechaInvalida = true;
        }

        if (fechaInvalida) {
            JOptionPane.showMessageDialog(null, "Error: La fecha de entrega no puede ser anterior a la de realización.");
            return;
        }

        eControl.setPaciente(pControl.buscarPacientePorDni(dniPaciente));
        eControl.setProfesional(profControl.buscarProfesional(matricula));
        eControl.setFechaRealizacion(new Fecha(dR, mR, aR));
        eControl.setFechaEntrega(new Fecha(dE, mE, aE));
        eControl.setEstado(estado);
        
        for (int cod : analisisTemporales) {
            eControl.agregarAnalisis(cod);
        }
        
        eControl.listaAgregarEstudio();
        eControl.prepararNuevoEstudio();

        ArchivoControlador archivoCtrl = new ArchivoControlador("pacientes.txt", "profesionales.txt", "estudios.txt");
        archivoCtrl.guardarEstudios(eControl.getListaEstudios());

        JOptionPane.showMessageDialog(null, "Estudio guardado correctamente.");

        txtDniEstudio.setText("");
        txtMatriculaEstudio.setText("");
        txtDiaRealizacion.setText("" + hoy.getDayOfMonth());
        txtMesRealizacion.setText("" + hoy.getMonthValue());
        txtAnioRealizacion.setText("" + hoy.getYear());
        txtDiaEntrega.setText("");
        txtMesEntrega.setText("");
        txtAnioEntrega.setText("");
        analisisTemporales.clear();
        txtAreaAnalisis.setText("");
    }//GEN-LAST:event_btnGuardarEstudioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ventanaPrincipal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAnioEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioEntregaActionPerformed

    private void cmbAnalisisDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnalisisDisponiblesActionPerformed
     
    }//GEN-LAST:event_cmbAnalisisDisponiblesActionPerformed

    
    private int convertirAEntero(String texto) {
        int numero = 0;
        for (int i = 0; i < texto.length(); i++) {
            char digito = texto.charAt(i);
            numero = (numero * 10) + (digito - '0');
        }
        return numero;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnalisis;
    private javax.swing.JButton btnEliminarAnalisis;
    private javax.swing.JButton btnGuardarEstudio;
    private javax.swing.JButton btnGuardarPaciente;
    private javax.swing.JButton btnGuardarProfesional;
    private javax.swing.JCheckBox chkObraSocial;
    private javax.swing.JComboBox<String> cmbAnalisisDisponibles;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtAnioEntrega;
    private javax.swing.JTextField txtAnioRealizacion;
    private javax.swing.JTextField txtApellidoPaciente;
    private javax.swing.JTextField txtApellidoProfesional;
    private javax.swing.JTextArea txtAreaAnalisis;
    private javax.swing.JTextField txtDiaEntrega;
    private javax.swing.JTextField txtDiaRealizacion;
    private javax.swing.JTextField txtDniEstudio;
    private javax.swing.JTextField txtDniPaciente;
    private javax.swing.JTextField txtMailPaciente;
    private javax.swing.JTextField txtMailProfesional;
    private javax.swing.JTextField txtMatriculaEstudio;
    private javax.swing.JTextField txtMatriculaProfesional;
    private javax.swing.JTextField txtMesEntrega;
    private javax.swing.JTextField txtMesRealizacion;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtNombreProfesional;
    private javax.swing.JTextField txtTelefonoPaciente;
    private javax.swing.JTextField txtTelefonoProfesional;
    // End of variables declaration//GEN-END:variables
}
